### PR TITLE
feat: Support OKX extension wallet to send Bitcoin.

### PR DESCRIPTION
**Pull request by lukema95**
Related: https://github.com/zeta-chain/docs/issues/348

### CODE REVIEW

**Comment by lukema95** [comment]
Now I can successfully send the testnet BTC with the following code, but the Testnet seems to lack the `getAccounts` interface at the moment:
```javascript
  const callOkxWallet = async (params: Params) => {
    if (!window.okxwallet) return alert("OKX wallet not installed")
    const okxwallet = window.okxwallet
    // const account = (await okxwallet?.bitcoinTestnet?.getAccounts())?.[0]
    // if (!account) return alert("No account found")
    try {
      const txHash = await okxwallet.bitcoinTestnet.send(
        {
          // from: account,
          from: "tb1pupdwvec0gy6kh5wl953fpmj33uww0994fpcxamk6rdk6kanzl6xsq35z77",
          to: params.tss,
          value: params.amount / 1e8,
          memo: `0x${params.contract}${params.message}`,
          memoPos: 1,
        }
      );
      return alert(`Broadcasted a transaction: ${txHash}`)
    } catch (e: any) {
      throw new Error(e.message || "Error sending OKX Bitcoin transaction")
    }

  }

```

**Comment by fadeev** [comment]
@lukema95 can you try using `okxwallet?.bitcoinTestnet?.connect()`, instead?

**Comment by lukema95** [comment]
> @lukema95 can you try using `okxwallet?.bitcoinTestnet?.connect()`, instead?

it worked, my bad😂

**Comment by fadeev** [comment]
@lukema95 thanks for working on this! As the example frontend repo is getting deprecated, I've migrated the changes proposed in this PR to the UniversalKit repo: https://github.com/zeta-chain/universalkit/

**Pull request closed without merging**
