### PR TITLE
add BTC transactions page

### PR DESCRIPTION
**Pull request by mikelord007**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new interface for managing Bitcoin transactions, allowing users to interact with multiple wallet providers (XDefi, UniSat, XVerse) seamlessly.
	- Added functionality for creating and signing Bitcoin transactions on the testnet.

- **Bug Fixes**
	- Implemented error handling to provide alerts for invalid inputs and wallet connection issues.

- **Chores**
	- Updated project dependencies to enhance security and cryptocurrency functionalities.

### CODE REVIEW

**Review by fadeev — CHANGES_REQUESTED** [review]
@mikelord007 please, fix TypeScript errors to make sure it builds with `yarn build`:

```
./app/btcintegration/page.tsx:53:28
Type error: Parameter 'params' implicitly has an 'any' type.

  51 |   }
  52 | 
> 53 |   const callXDefi = async (params) => {
     |                            ^
  54 |     if (!window.xfi) return alert("XDEFI wallet not installed")
  55 |     const wallet = window.xfi
  56 |     window.xfi.bitcoin.changeNetwork("testnet")
error Command failed with exit code 1.
```

**Comment by fadeev** [comment]
Overall, I think it works. I ran out of testnet BTC while testing this, but seems like Xverse is creating a tx.

### Xverse

Screenshot 2024-06-30 at 18 29 46

Screenshot 2024-06-30 at 18 29 49

Tx: c367cd678467d911c3b7c1b48c95aefaabd427636c655e3e80421b882ef33c5e (unconfirmed)

### XDEFI

Screenshot 2024-06-30 at 18 30 47

Screenshot 2024-06-30 at 18 31 01

Tx: 96fc207d4ee7e29d42c835509e963bed68aa4ae63a6bfadcf5c2814f80bbc1ab (unconfirmed)

**Comment by fadeev** [comment]
Hm, the issue with Xverse is that it's setting OP_RETURN as the first output. ZetaChain expects OP_RETURN to be the second output.

https://blockstream.info/testnet/tx/c367cd678467d911c3b7c1b48c95aefaabd427636c655e3e80421b882ef33c5e

Screenshot 2024-06-30 at 18 42 24

**Comment by fadeev** [comment]
@lukema95 please, review.

Once this is merged, please, add [OKX support](https://github.com/zeta-chain/docs/issues/348) to this. Thanks!

**Comment by mikelord007** [comment]
hey, have pushed fix for build errors and made OP_RETURN second output!

**Comment by fadeev** [comment]
@mikelord007 

Screenshot 2024-07-03 at 08 14 02

Screenshot 2024-07-03 at 08 14 10

Screenshot 2024-07-03 at 08 14 17

**Comment by fadeev** [comment]
Related: https://github.com/secretkeylabs/sats-connect/issues/143

**Comment by lukema95** [comment]
@mikelord007 @fadeev After I changed the code to look like this, I can sign multiple UTXOs normally:
```typescipt
async function createTransaction(
  publickkey: string,
  senderAddress: string,
  params: Params
): Promise<{ psbtB64: string; utxoCnt: number }> {
  const publicKey = hex.decode(publickkey)

  const p2wpkh = btc.p2wpkh(publicKey, bitcoinTestnet)
  const p2sh = btc.p2sh(p2wpkh, bitcoinTestnet)

  const recipientAddress = "tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur"
  if (!senderAddress) {
    throw new Error("Error: no sender address")
  }
  if (!recipientAddress) {
    throw new Error("Error: no recipient address in ENV")
  }

  const output = await fetchUtxo(senderAddress)

  const tx = new btc.Transaction({
    allowUnknowOutput: true,
  })

  let utxoCnt = 0;

  output.forEach((utxo) => {
    tx.addInput({
      txid: utxo.txid,
      index: utxo.vout,
      witnessUtxo: {
        script: p2sh.script,
        amount: BigInt(utxo.value),
      },
      witnessScript: p2sh.witnessScript,
      redeemScript: p2sh.redeemScript,
    })
    utxoCnt += 1;
  })

  const changeAddress = senderAddress

  const memo = `${params.contract}${params.message}`.toLowerCase()

  const opReturn = btc.Script.encode(["RETURN", Buffer.from(memo, "utf8")])

  tx.addOutputAddress(recipientAddress, BigInt(params.amount), bitcoinTestnet)
  tx.addOutput({
    script: opReturn,
    amount: BigInt(0),
  })
  tx.addOutputAddress(changeAddress, BigInt(800), bitcoinTestnet)

  const psbt = tx.toPSBT(0)

  const psbtB64 = base64.encode(psbt)

  return {psbtB64, utxoCnt}
}
```
```typescipt
async function signPsbt(psbtBase64: string, utxoCnt: number, senderAddress: string) {
  // Get the PSBT Base64 from the input

  if (!psbtBase64) {
    alert("Please enter a valid PSBT Base64 string.")
    return
  }

  const sigInputs = new Array(utxoCnt).fill(0, 0, utxoCnt).map((_, i) => i);
  console.log("Sign inputs:", sigInputs)

  try {
    const response = await Wallet.request("signPsbt", {
      psbt: psbtBase64,
      allowedSignHash: btc.SignatureHash.ALL,
      broadcast: true,
      signInputs: {
        [senderAddress]: sigInputs,
      },
    })

    if (response.status === "success") {
      alert("PSBT signed successfully!")
    } else {
      if (response.error.code === RpcErrorCode.USER_REJECTION) {
        alert("Request canceled by user")
      } else {
        console.error("Error signing PSBT:", response.error)
        alert("Error signing PSBT: " + response.error.message)
      }
    }
  } catch (err) {
    console.error("Unexpected error:", err)
    alert("Error while signing")
  }
}

```
```typescipt
  const callXverse = async (params: Params) => {
    const response = await Wallet.request("getAccounts", {
      purposes: [AddressPurpose.Payment],
      message: "Test app wants to know your addresses!",
    })

    if (response.status == "success") {
      const result = await createTransaction(
        response.result[0].publicKey,
        response.result[0].address,
        params
      )

      await signPsbt(result.psbtB64, result.utxoCnt, response.result[0].address)
    } else {
      alert("wallet connection failed")
    }
  }
```

**Comment by mikelord007** [comment]
@lukema95 thanks for that, it successfully signs multiple UTXO's now
@fadeev not sure how to encode it to binary

**Comment by fadeev** [comment]
@mikelord007 thanks for working on this! As the example frontend repo is getting deprecated, I've migrated the changes proposed in this PR into the UniversalKit repo: https://github.com/zeta-chain/universalkit/pull/8

**Pull request closed without merging**
